//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class FisaMedicala
    {
        public string pacient_cnp { get; set; }
        public string descriere { get; set; }
        public string nume_doctor { get; set; }
        public string data { get; set; }
        public int id { get; set; }
    }
}
