//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicDBEntities3 : DbContext
    {
        public MedicDBEntities3()
            : base("name=MedicDBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<datamedic> datamedics { get; set; }
        public virtual DbSet<FisaMedicala> FisaMedicalas { get; set; }
        public virtual DbSet<MedicDetail> MedicDetails { get; set; }
        public virtual DbSet<PacientDetail> PacientDetails { get; set; }
        public virtual DbSet<Pacienti> Pacientis { get; set; }
        public virtual DbSet<Programare> Programares { get; set; }
    }
}
